
apiVersion: v1
kind: ReplicationController
metadata:
   name: firstapp-rc
spec:
   replicas: 5
   selector:
      app: firstapp
   template:
      metadata:
        labels:
          app: firstapp
      spec:
        containers:
         - name: firstapp-container
           image: jenkins:2.60.3
           ports:
              - containerPort: 8080