
apiVersion: apps/v1
kind: Deployment
metadata:
   name: javaapp-deploy
   labels:
      app: javaapp
spec:
   replicas: 2
   selector: 
      matchLabels:
          app: javaapp
   template:
      metadata:
          labels:
             app: javaapp
      spec:
         containers:
           - name: javaapp-container
             image: maha4iac/myonlineapp:1
             ports:
               - containersPort: 8080