
apiVersion: v1
kind: ReplicationController
metadata:
   name: firstapp-rc
spec:
   replicas: 2
   selector:
      app: firstapp
      version: 2.6.2
   template:
      metadata:
        labels:
          app: firstapp
          version: 2.6.2
      spec:
        containers:
         - name: firstapp-container
           image: maha4iac/myjavaapp20jan22:2
           ports:
              - containerPort: 8080