
apiVersion: v1
kind: ReplicationController
metadata:
   name: onlineapp-rc
spec:
   replicas: 3
   selector:
      app: firstapp
   template:
      metadata:
        lables:
          app: firstapp
      spec:
        containers:
         - name: firstapp-container
           image: nitesh09nck/javaapp:1
           ports:
              - containerPort: 8080